services:

    webserver:
        build:
            context: ./docker/webserver
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            APP_USER_ID: '${APP_USER_ID}'
            APP_GROUP_ID: '${APP_GROUP_ID}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - './docker/webserver/php.ini:/etc/php/8.2/cli/conf.d/99-application.ini'
            - './docker/webserver/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
            - './docker/webserver/entrypoint.sh:/usr/local/bin/entrypoint.sh'
        links:
            - mysql
            - redis
            - meilisearch
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
            meilisearch:
                condition: service_healthy

    adminer:
        image: adminer
        ports:
            - '${ADMINER_PORT:-8080}:8080'
        links:
            - mysql
        depends_on:
            mysql:
                condition: service_healthy

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'

    mysql:
        image: mysql:8
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 10s

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 10s

    meilisearch:
        image: 'getmeili/meilisearch:latest'
        platform: linux/x86_64
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'meilisearch:/data.ms'
        environment:
            MEILI_HTTP_ADDR: 0.0.0.0:7700
            MEILI_MASTER_KEY: '${MEILISEARCH_KEY}'
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s

volumes:
    mysql:
        driver: local
    redis:
        driver: local
    meilisearch:
        driver: local
